version: '3'

services: 
  app:
    build: .
    container_name: malbums_app
    entrypoint: 'dockerize -wait tcp://db:3306 -timeout 45s .docker/entrypoint.sh'
    ports: 
      - 3001:3001
    volumes: 
      - .:/home/node/app
    depends_on: 
      - db
    
  db: 
    build: .docker/mysql/
    container_name: malbums_db
    ports: 
      - 3306:3306
    tty: true
    volumes: 
      - .docker/dbdata:/var/lib/mysql
    env_file: 
      - .docker/mysql/.env
